# 1. Suma y producto escalar combinados

<span style="color:blue">Ejercicio: Usando los procedimientos add y mult_vector_escalar definidos anteriormente, calcular:   
{$\alpha$[1,2]+[3,4] : $\alpha$$\in$$\mathbb{R}$, 0$\leq$$\alpha$$\leq$1, con una precision de dos decimales}</style>

In [1]:
def add(v,w):
    return [v[0]+w[0],v[1]+w[1]]

In [2]:
def mult_vector_escalar(alpha,v):
    return [alpha*v[i] for i in range(len(v))]

In [3]:
List = [mult_vector_escalar(alpha/100.,[1,2]) for alpha in range(101)]

In [4]:
for v in List:
    print(add(v,[3,4]))
   

[3.0, 4.0]
[3.01, 4.02]
[3.02, 4.04]
[3.03, 4.06]
[3.04, 4.08]
[3.05, 4.1]
[3.06, 4.12]
[3.07, 4.14]
[3.08, 4.16]
[3.09, 4.18]
[3.1, 4.2]
[3.11, 4.22]
[3.12, 4.24]
[3.13, 4.26]
[3.14, 4.28]
[3.15, 4.3]
[3.16, 4.32]
[3.17, 4.34]
[3.18, 4.36]
[3.19, 4.38]
[3.2, 4.4]
[3.21, 4.42]
[3.22, 4.44]
[3.23, 4.46]
[3.24, 4.48]
[3.25, 4.5]
[3.26, 4.52]
[3.27, 4.54]
[3.2800000000000002, 4.5600000000000005]
[3.29, 4.58]
[3.3, 4.6]
[3.31, 4.62]
[3.32, 4.64]
[3.33, 4.66]
[3.34, 4.68]
[3.35, 4.7]
[3.36, 4.72]
[3.37, 4.74]
[3.38, 4.76]
[3.39, 4.78]
[3.4, 4.8]
[3.41, 4.82]
[3.42, 4.84]
[3.43, 4.86]
[3.44, 4.88]
[3.45, 4.9]
[3.46, 4.92]
[3.4699999999999998, 4.9399999999999995]
[3.48, 4.96]
[3.49, 4.98]
[3.5, 5.0]
[3.51, 5.02]
[3.52, 5.04]
[3.5300000000000002, 5.0600000000000005]
[3.54, 5.08]
[3.55, 5.1]
[3.56, 5.12]
[3.57, 5.14]
[3.58, 5.16]
[3.59, 5.18]
[3.6, 5.2]
[3.61, 5.22]
[3.62, 5.24]
[3.63, 5.26]
[3.64, 5.28]
[3.65, 5.3]
[3.66, 5.32]
[3.67, 5.34]
[3.68, 5.36]
[3.69, 5.38]
[3.7, 5.4]
[3.71, 5.42]
[3.

# 2. El secreto perfecto

Reprenta la encriptación de la adicción de un n-vector a un n-vector de GF(2)  

![No se puede mostrar](https://www.salvat.com/colecciones/mortadelo-y-filemon/res/img/detalles-characters.png)

<span style="color:orange">Ejemplo: Mortadelo y Filemón usan como clave el siguiente vector:</style>  
> <span style="color:orange">**k**=[0,1,0,0,1,0,1,0,1,0]</style>  

<span style="color:orange">Mortadelo quiere enviarle a Filemón el siguiente mensaje:</style>  
> <span style="color:orange">**p**=[0,0,0,1,1,1,0,1,0,1]</style>  

<span style="color:orange">Mortadelo encripta su mensaje añadiendo k:</style>  
> <span style="color:orange">**c**=**p**+**k**=[0,0,0,1,1,1,0,1,0,1]+[0,1,0,0,1,0,1,0,1,0]=[0,1,0,1,0,1,1,1,1,1]</style>  

<span style="color:orange">Cuando Filemón recibe el mensaje, lo desencripta añadiendo **k** a lo que ha recibido</style>  
> <span style="color:orange">**p**=**c**+**k**=[0,1,0,1,0,1,1,1,1,1]+[0,1,0,0,1,0,1,0,1,0]=[0,0,0,1,1,1,0,1,0,1]</style>    

<span style="color:orange">que es el mensaje original</style>    
  
 <span style="color:blue">Ejercicio: ¿Cómo lo harías en Python? (Definiendo un procedimiento)</style>  

In [5]:
def addGF2 (u,v):
    answer = [0]*(len(u))
    for i in range(len(u)):
        if u[i] > 1 or v[i] >1: 
            print("Los vectores no pertenecen a GF2")
            break
        elif u[i] < 0 or v[i] < 0:
            print("Los vectores no pertenecen a GF2")
            break
        elif len(u)!=len(v):
            print ("Los vectores no tienen la misma dimension")
            break
        else:
            if u[i] == v[i]:  
                answer[i] = 0
            else:
                answer[i] = 1
    return answer
            

In [6]:
k=[0,1,0,0,1,0,1,0,1,0]
p=[0,0,0,1,1,1,0,1,0,1]

c= addGF2(p,k)
c

[0, 1, 0, 1, 0, 1, 1, 1, 1, 1]

In [7]:
print("La suma de c y k sera: "+str(addGF2(c,k))+" que es igual a p="+str(p))

La suma de c y k sera: [0, 0, 0, 1, 1, 1, 0, 1, 0, 1] que es igual a p=[0, 0, 0, 1, 1, 1, 0, 1, 0, 1]


# 3. Ejercicio: coste total o beneficio

![No se puede mostrar](https://maltosaa.com.mx/wp-content/uploads/bigstock-Beer-Glass-And-Hops-593384301.jpg)

<span style="color:blue">Supongamos que D es el conjunto de algunos ingredientes de la cerveza: </style>
> <span style="color:blue">D={lúpulo, malta, agua, levadura}</style>  

<span style="color:blue">Por otro lado tenemos el vector coste:</style>  
> <span style="color:blue">coste={lúpulo: 2,5€, malta: 1.5€, agua: 0.006€, levadura: 0,45€}</style>  

<span style="color:blue">Por último tenemos el vector cantidad con lo necesario para hacer una cerveza:</style>  
> <span style="color:blue">cantidad={lúpulo: 6u, malta: 14u, agua: 7u, levadura: 11u}</style>  

<span style="color:blue">¿Cuánto cuesta hacer una cerveza?</style> 

In [8]:
def producto_vectorial(u,v):
    return sum(u[i]*v[i] for i in range(len(u)))

In [9]:
round(producto_vectorial([2.5,1.5,0.006,0.45],[6,14,7,11]),2)

40.99

# 4.Ejercicio:  
<span style="color:blue">¿Cómo escribirías cada uno de los vectores {[3,0,0],[0,2,0],[0,0,1]} como combinación lineal de {[2,0,1],[1,0,2],[2,2,2]}?
Escribe las combinaciones lineales en Python. Seguramente tenga que definir una nueva suma.</style>  

In [10]:
def addn3(v,w,z):
    return[v[i]+w[i]+z[i] for i in range(len(v))]

In [11]:
def mult_vector_escalar(alpha,v):
    return [alpha*v[i] for i in range(len(v))]

In [12]:
print("[3,0,0] = 2*[2,0,1] - 1*[1,0,2] = "
      +str(addn3(mult_vector_escalar(2,[2,0,1]),
                 mult_vector_escalar(-1,[1,0,2]),
                 mult_vector_escalar(0,[2,2,2]))))

[3,0,0] = 2*[2,0,1] - 1*[1,0,2] = [3, 0, 0]


In [13]:
print("[0,2,0] = -2/3*[2,0,1] - 2/3*[1,0,2] + 1*[2,2,2] = "
      +str(addn3(mult_vector_escalar((-2/3.),[2,0,1]),
                 mult_vector_escalar((-2/3.),[1,0,2]),
                 mult_vector_escalar(1,[2,2,2]))))

[0,2,0] = -2/3*[2,0,1] - 2/3*[1,0,2] + 1*[2,2,2] = [0.0, 2.0, 0.0]


In [14]:
print("[0,0,1] = -1/3*[2,0,1] + 2/3*[1,0,2] = "
      +str(addn3(mult_vector_escalar((-1/3.),[2,0,1]),
                 mult_vector_escalar((2/3.),[1,0,2]),
                 mult_vector_escalar(0,[2,2,2]))))

[0,0,1] = -1/3*[2,0,1] + 2/3*[1,0,2] = [0.0, 0.0, 1.0]


# 5. Ejercicio:  
* Si AB = AC, en general no es cierto que B = C.  

<span style="color:blue"> Ejercicio: Dadas las matrices $
  A=
  \left[ {\begin{array}{cc}
   2 & -3 \\
   -4 & 6\\
  \end{array} } \right]
$ , $
  B=
  \left[ {\begin{array}{cc}
   8 & 4 \\
   5 & 5\\
  \end{array} } \right]
$
y $
  C=
  \left[ {\begin{array}{cc}
   5 & -2 \\
   3 & 1\\
  \end{array} } \right]
$, queremos verificar que AB=AC pero que B≠C.</style> 

In [15]:
import numpy as np

A=np.array([
    [2,-3],
    [-4,6]
])

B=np.array([
    [8,4],
    [5,5]
])

C=np.array([
    [5,-2],
    [3,1]
])

In [16]:
print("AB es igual a:")
np.dot(A,B)

AB es igual a:


array([[ 1, -7],
       [-2, 14]])

In [17]:
print("AC es igual a:")
np.dot(A,C)

AC es igual a:


array([[ 1, -7],
       [-2, 14]])

# 6. Ejercicio:  
<span style="color:blue"> Ejercicio: Dadas la matriz $
  A=
  \left[ {\begin{array}{cc}
   3 & -6 \\
   -1 & 2\\
  \end{array} } \right]
$ , construye una matriz B de 2 × 2 tal que AB sea igual a la matriz cero. Las columnas de B no deben ser iguales entre sí y deben ser distintas de cero.
.</style> 

In [18]:
import numpy as np

A=np.array([
    [3,-6],
    [-1,2]
])

In [19]:
print("tenemos las siguientes ecuaciones:")
print("3*B[0,0] - 6*B[1,0] = 0")
print("3*B[0,1] - 6*B[1,1] = 0")
print("-1*B[0,0] - 2*B[1,0] = 0")
print("-1*B[0,1] - 2*B[1,1] = 0")

tenemos las siguientes ecuaciones:
3*B[0,0] - 6*B[1,0] = 0
3*B[0,1] - 6*B[1,1] = 0
-1*B[0,0] - 2*B[1,0] = 0
-1*B[0,1] - 2*B[1,1] = 0


In [20]:
print("nos vale cualquier matriz que cumpla que B[0,0]=2*B[1,0] y que B[0,1]=2*B[1,1]")
print("por ejemplo:")

B=np.array([
    [2,4],
    [1,2]   
])
B

nos vale cualquier matriz que cumpla que B[0,0]=2*B[1,0] y que B[0,1]=2*B[1,1]
por ejemplo:


array([[2, 4],
       [1, 2]])

In [21]:
np.dot(A,B)

array([[0, 0],
       [0, 0]])

# 7. Regla de Sarrus para el determinante de orden 3

Sea A una matriz de orden 3, su determinante:
$\left| {\begin{array}{cc}
   a & b & c\\
   d & e & f\\
   g & h & i\\
  \end{array} } \right|=aei+bfg+cdh-(ceg+bdi+afh)$
<span style="color:orange"> Ejemplo: Vamos a calcular el determinante de $
  A=
  \left[ {\begin{array}{cc}
   1 & -4 & 2\\
   -2 & 8 & -9\\
   -1 & 7 & 0\\
  \end{array} } \right]
$ usando la ley de Sarrus.  
detA=$1 \cdot 8 \cdot 0+(-2) \cdot 7 \cdot 2+(-1) \cdot (-4) \cdot (-9)-[(2 \cdot 8 \cdot (-1)+0 \cdot (-2) \cdot (-4)+1 \cdot 7 \cdot (-9)]=15$  </style>

<span style="color:blue">Ejercicio: ¿Cómo lo haríamos en Python?</style>

In [22]:
import numpy as np

A=np.array([
    [1,-4,2],
    [-2,8,-9],
    [-1,7,0]
])

detA=A[0,0]*A[1,1]*A[2,2]+A[0,1]*A[1,2]*A[2,0]+A[0,2]*A[1,0]*A[2,1]-(A[0,2]*A[1,1]*A[2,0]+A[0,1]*A[1,0]*A[2,2]+A[0,0]*A[1,2]*A[2,1])
detA

15

# 8.<span style="color:blue"> Ejercicio:  
Sabemos que hay un modo directo en Python para calcular los rangos. Calcula el número de soluciones de estos tres sistemas de ecuaciones empleándolo.</style> 

> <span style="color:blue">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:blue">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:blue">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

In [23]:
import numpy as np


A=np.array([
    [1,-2,1],
    [0,2,-8],
    [-4,5,9]
])

Aamp=np.array([
    [1,-2,1,0],
    [0,2,-8,8],
    [-4,5,9,-9]
])

def sistema(matriz,matriz_ampliada):
    if np.linalg.matrix_rank(matriz)==np.linalg.matrix_rank(matriz_ampliada):
        print("El sistema tiene solucion")
        if np.linalg.matrix_rank(matriz)==len(matriz[0]):
            print("SCD con "+str(np.linalg.matrix_rank(matriz))+" soluciones.")
        else:
            print("SCI")
    else:
        print("El sistema no tiene solucion")
        
sistema(A,Aamp)

El sistema tiene solucion
SCD con 3 soluciones.


> <span style="color:blue">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:blue">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:blue">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [24]:
B=np.array([
    [0,1,-4],
    [2,-3,2],
    [5,-8,7]
])

Bamp=np.array([
    [0,1,-4,8],
    [2,-3,2,1],
    [5,-8,7,1]
])

sistema(B,Bamp)

El sistema no tiene solucion


> <span style="color:blue">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:blue">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:blue">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [25]:
C=np.array([
    [1,0,1],
    [2,3,1],
    [3,3,2]
])

Camp=np.array([
    [1,0,1,2],
    [2,3,1,3],
    [3,3,2,5]
])

sistema(C,Camp)

El sistema tiene solucion
SCI


# 9. Función lineal  

Dados $\mathbb{V}$ y $\mathbb{W}$, espacios vectoriales de $\mathbb{F}.  
Supongamos que una función f: \mathbb{V}$ $\longrightarrow$ $\mathbb{W}$ satisface dos propiedades:  
* Para cada vector v en V y cada escalar α en F, f (αv) = αf(v)  
* Por cada dos vectores u y v en V, f (u + v) = f (u) + f (v)  

Entonces llamamos a f **función lineal**.  

<span style="color:blue"> Ejercicio:  
Comprobar que r(x,y) para un ángulo $\theta$ es una función lineal.</style> 

   
<span style="color:orange"> Definimos r([x,y]) = función rotación $\theta$º.  
Sabemos que r([x , y ]) = M ∗ [x , y ] para alguna matriz M .</style>   
> * <span style="color:orange">Sabemos que r([1,0])=[cos$\theta$,sin$\theta$]  .</style>  
> * <span style="color:orange">Sabemos que r([0,1])=[-sen$\theta$,cos$\theta$]  .</style>  

<span style="color:orange">Por lo tanto:  
$
  M =
  \left[ {\begin{array}{cc}
   cos\theta & -sin\theta \\
   sin\theta & cos\theta \\
  \end{array} } \right]
$</style> 

Primera condición: r(a*v) = a*r(v)

v = (x,y); av = (ax,ay)

r(v) = M*(x,y) = (xcosT - ysenT, xsenT + ysenT)

r(av) = M*(ax,ay) = (axcosT - aysenT, axsenT + aysenT) = a(xcosT - ysenT, xsenT + ysenT)

=> r(a*v) = a*r(v) Se cumple.

Segunda condición: r(u+v) = r(u) + r(v)

v = (x,y); u = (w,z)

r(v) = M*(x,y) = (xcosT - ysenT, xsenT + ycosT)  
r(u) = M*(w,z) = (wcosT - zsenT, wsenT + zcosT)

r(u) + r(v) = (xcosT - ysenT + wcosT - zsenT, xsenT + ycosT + wsenT + zcosT)

r(u+v) = M*(x+w,y+z) = (xcosT + wcosT - ysenT - zsenT, xsenT + wsenT + ycosT + zcosT)

Se cumple.



# 10. Representación de las coordenadas de un vector  

La representación de las coordenadas del vector **v** en términos de a<sub>1</sub>,. . . , a<sub>n</sub> es el vector [α1, ..., αn] tal que  
> **v** = α<sub>1</sub> a<sub>1</sub> + ... + α<sub>n</sub> a<sub>n</sub>  

En este contexto, los coeficientes se llaman **coordenadas**.  

<span style="color:orange"> Ejemplo:  
El vector v = [1, 3, 5, 3] es igual a 1[1,1,0,0]+2[0,1,1,0]+3[0,0,1,1].  
Por tanto, la representación en coordenadas de v en términos de los vectores [1,1,0,0],[0,1,1,0],[0,0,1,1] es [1,2,3]. </style>   

<span style="color:blue"> Ejercicio:  
¿Cuál es la representación coordenada del vector v= [6, 3, 2, 5] en términos de los vectores [2, 2, 2, 3], [1, 0, −1, 0], [0, 1, 0, 1]?</style> 

(6,3,2,5) = a*(2,2,2,3) + b*(1,0,-1,0) + c*(0,1,0,1)  

6 = 2a + b  
3 = 2a + c  
2 = 2a -b  
5 = 3a + c

b = 2a - 2; 6 = 2a + 2a - 2; 4a = 8 => a = 2
b = 2  
c = -1

las coordenadas de v en términos de los vectores dados son (2,2,-1)


# 11.<span style="color:blue"> Ejercicio:  
Supongamos que queremos diseñar la red de internet para el otro campus universitario.  
La red debe lograr la misma conectividad que el grafo de entrada.  
Una arista representa un posible cable.  
El peso de la arista es el coste de instalar el cable.  
Nuestro objetivo es minimizar el coste total, usando el algoritmo Grow y el algoritmo Shrink.  </style> 

![No se puede mostrar](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFXlVv3ueokDdT65uKQHaV5zO2Ng1N3OJODJ2kxlF4CKp-f-8QPw) 

Pesos:

Biomed-Pembroke Campus (2)  
Pembroke Campus-Athletic Complex(7)  
Biomed-Athletic complex (9)

Resolviendo con el algoritmo grow:

S=0

Aristas en orden creciente:

2,7,9  
Biomed-Pembroke Campus (B-P), Pembroke Campus-Athletic Complex (P-A), Biomed-Athletic complex (B-A)  

Añadimos a S la primera arista:

S={(B-P)}

Ya tenemos los nodos Biomed y Pembroke Campus, faltaría Athletic Complex.

Añadimos la arista de menor peso que nos incorpora este último nodo (P-A).

S queda finalmente de la siguiente manera:

S={(B-P), (P-A)}

# 12.<span style="color:blue"> Ejercicio:  
Sea la matriz $
  M=
  \left[ {\begin{array}{cc}
   1 & 0  & 0 & 5 \\
   0 & 2  & 0 & 7 \\
   0 & 0  & 3 & 9 \\
  \end{array} } \right]
$. Calcular el rango por filas y por columnas usando Python.</style> 

In [26]:
import numpy as np

M=np.matrix([
    [1,0,0,5],
    [0,2,0,7],
    [0,0,3,9]
])

np.linalg.matrix_rank(M)

3

In [27]:
N=np.transpose(M)

np.linalg.matrix_rank(N)

3

# 13. (Opcional) Algoritmo para transformar una matriz en una matriz escalonada  

<span style="color:blue"> Ejercicio 13 (opcional):  
Crea un algoritmo que transforme una matriz cualquiera en GF(2) en una matriz escalonada.</style> 

In [28]:
import numpy as np

def algoritmo_infernal(A):
    for i in range(0,len(A)):  
        for j in range(0,len(A[i])):
            if i>0 and i >= j:
                #A[i,j] en este punto son los elementos que hay que hacer 0
                A[i,j]=0 #jejeje
                    
    return A



A=np.array([
    [1,1,0,1,0],
    [1,0,0,1,0],
    [0,1,1,0,1]
])

algoritmo_infernal(A)


array([[1, 1, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Me parece un problema muy complicado. Creo que el concepto sería más o menos así:

*En primer lugar, comprobar si el elemento 1,1 (A[0,0]) es un 1 o un 0. Si es un 0 hay que cambiar esta fila por la primera fila cuyo primer elemento sea un 1 (A[i,0]==1).  

*Luego habría que empezar un bucle por filas y columnas, supongo que valdría algo como lo que he definido arriba. El problema es que para cada elemento que hay que hacer 0 hay que sumar la fila con una fila superior que tenga un 1 en la misma columna y 0 en las anteriores.  

*Por eso me parece muy dificil hacerlo para cualquier matriz. No sé si se me escapa algo pero no creo que sea capaz de conseguirlo sin dedicarle una enorme cantidad de tiempo de modo que lamentablemente te entrego esta chapucilla.  

*Cuando publiques una solución la estudiaré con atención y seguramente me de de cabezazos contra la pared por no habérseme ocurrido, así son estas cosas!

# 14.<span style="color:blue"> Ejercicio 14:  
Modificar lo necesario en los algoritmos para que funcionen y calculen el problema de la casa en llamas.</style>

In [29]:
import numpy as np
import math

def producto_vectorial(u,v):
    return sum(u[i]*v[i] for i in range(len(u)))
def mult_vector_escalar(alpha,v):
    return [alpha*v[i] for i in range(len(v))]
def resta_vectores(v,w):
    return[v[i]-w[i] for i in range(len(v))]


def proy_paralela(b,a):
    if producto_vectorial(a,a) >10^(-20):
        sigma=producto_vectorial(b,a)/producto_vectorial(a,a)
    else:
        sigma=0
    return mult_vector_escalar(sigma,a)

def proy_ortogonal(b,a):
    return resta_vectores(b,proy_paralela(b,a))



a=[6.,2.]

b=[2.,4.]

u=proy_paralela(b,a)
v=proy_ortogonal(b,a)

print("La distancia es "+str(round(math.sqrt(producto_vectorial(v,v)),2)))

La distancia es 3.16


# COMENTARIOS

En general me quedo satisfecho con este módulo. Como ya comenté en la encuesta de estadística, el formato de ir siguiendo un notebook en clase me parece muy acertado y también de cara a hacer la práctica, que queda perfectamente estructurada y no hay duda respecto a lo que se pide.

En cuanto a la asignatura, lo que es la parte matemática me ha parecido por lo general sencilla pero a cambio la parte de programación me ha permitido ver muchas cosas que no conocía así que para mi una cosa compensa la otra.

En cuanto a la forma de dar las clases, pues como ya dije en el primer módulo se agradece mucho tu energía y que hagas las clases amenas. Aunque este módulo en concreto no he podido asistir a todas las clases en directo, es algo fundamental al dar una clase tan larga y en horario nocturno. También se nota que pones todo el empeño posible en contestar todas las dudas que surjan y en que todo el mundo quede satisfecho antes de pasar de uno a otro punto. Todo eso lo notamos desde casa aunque no hablemos mucho!

